CREATE TABLE IF NOT EXISTS world_state (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    ground JSON NOT NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
